# SHITE_META
#+title: Hi, I'm Aditya Athalye.
#+subtitle: Sentient Learning Machine & Human General Intelligence.
#+summary: Stuff I like to nerd about.
#+author: Adi
#+tags: index
#+date: 2021-11-10
# SHITE_META

*/eval/apply [fn:1] is my credo/*. To */eval/* is to think culture over
strategy, humans over technology, systems over hacks, workflows over tools. To
*/apply/* is to Design by /subtraction/ [fn:2], engineer for simplicity, produce
output iteratively, ship continuously.

*/Learn generously is my favourite self-directive [fn:3]./* One stands on the
shoulders of giants. One has received much generosity. One benefits greatly from
contributions to the public commons.

The dashing duo of /eval/apply/ and /learn generously/ pervades all that I [[./posts/index.html][think]],
[[https://github.com/adityaathalye/clojure-by-example][teach]], [[https://confengine.com/user/aditya-athalye-1][speak]], [[https://inclojure.org/][organise]], [[https://news.ycombinator.com/submitted?id=adityaathalye][share]], [[https://github.com/adityaathalye/][code]],
and what I am doing /[[./now.html#main][now]]/.

*/Thoughtful [[mailto:hello@evalapply.org][email chats]] are welcome!/* Pet [[./posts/index.html#tags-index-list][topics]] include software, systems,
complexity, architecture, functional programming, and Clojure.

#+begin_export html
<div class="stack">
<div>Ah, and I email occasional newsletters too.</div>
<form class="footer cluster"
      action="https://buttondown.email/api/emails/embed-subscribe/evalapply"
      method="post" target="popupwindow"
      onsubmit="window.open('https://buttondown.email/evalapply','popupwindow')">
  <input type="email" name="email" id="bd-email">
  <span>
    <input type="submit" value="Get the eval/apply dispatch">
    <em>(thanks, <a href="https://buttondown.email" target="_blank">Buttondown</a>!)</em>
  </span>
</form>
<div></div>
</div>
#+end_export

[fn:1] Computing pioneer Alan Kay dubbed /eval/apply/ the
[[https://www.gnu.org/software/mes/manual/html_node/LISP-as-Maxwell_0027s-Equations-of-Software.html][Maxwell’s Equations of Software]].
It is such a stunningly compact and fundamental descriptor of all of computing.
To me, the concept also embodies similarly powerful non-dualities; think/do,
diffuse/focus, abstract/concretise. Over time, it became my /way/.

[fn:2] /"It is not daily increase but daily decrease, hack away the unessential.
The closer to the source, the less wastage there is."/ --- Bruce Lee

[fn:3]  /Learn generously/ is a "[[https://www.recurse.com/self-directives][self-directive]]"
coined by the gentlepeople at my favourite programmers' community,
the Recurse Center.
#+html:<div class="box invert"><div class="footnotes rc-scout"></div></div>
