# SHITE_META
#+title: Eval/Apply for fun and profit.
#+summary: A now page inspired by sive.rs/now and nownownow.com
#+author: Adi
#+tags: now
#+date: 2023-03-24
# SHITE_META

-----
* What I am doing now

/Updated:/ April 2023

#+begin_quote
"This is [[https://nownownow.com/about][a now page]], and if you have your own site,
[[https://nownownow.com/about][you should make one]], too."

--- [[https://sive.rs/now][Derek Sivers]]
#+end_quote


*2023 is dedicated to total reinvention.*

A dead past is being firewalled. Accumulated baggage is being tagged for
eventual garbage collection. The mind's mechanics are being revised. The body is
being repaired and upgraded. New experiences are being opted into. By learning
to see with new eyes, a fresh vision of self, world, and life is appearing.

#+begin_quote
*Analogy:* Adopt "diffuse mode" mindset to reinvent, and "focus mode" mindset
to then re-build.
#+end_quote

*2023 is professional reinvention number three.*

My 20s were full of MBA-type work as well as one failed attempt at a startup.
My 30s became about software engineering. The 40s seem to have begun with yet
another pivot; toward solo enterprise. Suit and hoodie are amalgamating.

#+begin_quote
*Objective:* Test one's wits, skills, capabilities, knowledge in the exacting
crucible of makin' and sellin' stuff.
#+end_quote

*2023 is sabbatical number four.*

My sabbaticals have been times of hardcore reading, study, and hands-on
use of new knowledge. Literally living /eval/apply/; I learn things and
test myself by landing paid gigs for what I have learned. Let's see where this
one goes.

#+begin_quote
*Insight:* Making sabbaticals work is primarily about psychology, not money.
#+end_quote

*Yes, and...*

An improv-style approach is being applied to break into the present, and to also
break out of the "no, but" style psychological ossification that is common
experience, after having lived a bit (but not a bit too much). Living a bit too
much seems to engender a "like, whatever" style of psychological regression.
That feels /so/ much harder to escape. Anyway, we're escaping "no, but" out here,
and if you call this method improv-ing oneself, we won't complain.

#+begin_quote
*Experience:* I am about a year into what I've dubbed the "/Yes, and/ method of
reinvention". And yes, I heartily recommend it to anyone who will listen.
#+end_quote

*Small is beautiful; the lifelong trend continues.*

Career-start was the first time I truly exerted my volitional muscles, and chose
to work with/at small and medium companies instead of the socially approved giant
MNC circuit. That drive has run through my MBA twenties, tech thirties, and seems
to be the /telos/ for the, shall we say, /[[https://goodreads.com/book/show/37570605-company-of-one][company of one]]/ forties?

#+begin_quote
*Principle:* When reinventing, known-good legacy need not be discarded.
It may in fact be the very thing to subtract down to, and rebuild from, anew.
#+end_quote

*2021 and 2022*

#+begin_quote
"A rebirth requires a death."

--- Yours truly
#+end_quote

'nuff said.

*2020*

/This/ would be /The Year Of Total Reinvention/, had Certain World Events
not intervened. Still, it began swimmingly, hacking Clojure code at a consulting
gig, organising [[https://inclojure.org/][IN/Clojure 2020]], and experiencing
an amazing programmer's retreat at the [[https://recurse.com][Recurse Center]].

*Pre-2020*

Faded into the mists of time. [[#what-i-am-doing-now][GOTO now]].
