# SHITE_META
#+title: Baby don't hurry, don't stop (feat. Melancholy)
#+summary: Here lies melancholy that I put to paper from a particularly deep hole, not too long ago. It may ruin your day, or it may make you feel a little bit understood about your dark moments. Your mileage will vary.
#+author: Adi
#+date: 2022-02-14
#+updated: 2022-02-14
#+tags: meta mentalhealth
#+include_toc: no
# SHITE_META

This is how I struggle from time to time. It is not pretty. These days it's
been a lot more. Thankfully, it is not a constant. Instead of reading this,
you should want to listen to Alain de Botton.
- [[https://www.youtube.com/watch?v=Aw1oLtuJOXQ][on Pessimism]]
- [[https://www.youtube.com/watch?v=jJ6K_f7oSdg][on Love]]
- [[https://www.youtube.com/watch?v=W9X7u-MeJz0][on an Emotional Education]]

For here lies melancholy that I put to paper from a particularly deep hole,
not too long ago. It may ruin your day, or it may make you feel a little bit
understood about your dark moments. And it---unlike Alain's teachings---will
certainly not help you find a way through.

Your mileage /will/ vary.

Today was one of those days.

When the feeling hit like a slap in the face. Again. Just how much of my
youth burned in self-doubt, fear, self-shame, akrasia.

Twenty years of young adulthood incinerated by mine own hand, before my own
eyes, and I did nothing to save it.

Sigh.

This life is singular. It is not ours to have. It is not ours to end. It is
ours to embrace as a gift to give away.

The gift is a chance to become all that we can become. We cannot become, if we
keep staring down at ourselves from imagined imaginations of others. What if
I can't do it? What if I fail? What if nobody likes me? I am not /this/. I am
not /that/. I'll never get /there/. /I/ am not even someone. That is the root
of all self-doubt and fear and shame. A never-being in the here and now. A
never-learning about oneself. A never-knowing of feeling alive. The kind of
poverty that material things cannot end.

Looking from the outside makes us pressure and twist ourselves into the imagined
mould. But the mould changes before we're done. And we start again. The cycle is
endless, relentless. We go faster, but it changes faster. And we forget ourselves.

If there is one gift we can give to another, especially a young one, it would
be to show them how to live this: "Don't hurry, don't stop.". To learn to /do/,
without fearing the unknown, knowing failure without shame, with kindness, with
oneself, without hurry.

Hurry forces pause. Not pausing breaks us. So many break forever. Never becoming.

So many learn too late, that they only know to hurry, that they can't slow down.
Once perhaps, long ago, they peered inside their mould and saw nothing. It's
not that nothing exists, it's that they never learned to see. And so all that
remained was to dwell in the future; remoulding faster and faster until the
breakdown. Or worse, to delve into the past, in endless revisions of discarded
moulds to reach an imagined now that never will come to pass. If there is a
metaverse, it is this.

This prisoners' game of imagined imaginations.

Fantasies rooted in fantasy.

Maybe it's not too late for you. Maybe it's not too late for me.

I hope it isn't.

But if it is too late, then I hope we come back, you and I.

For a rebirth requires a death.

#+begin_quote
/"It is better to do something continuously, perpetually and untiringly than to hustle and fail./
/If you hurry, you must rest. If you want to keep going without resting, then you mustn’t hurry./

/Don’t hurry, don’t stop.”/

--- [[https://en.wikipedia.org/wiki/Kintar%C5%8D_Hattori][Kintarō Hattori]]
#+end_quote
